%YAML:1.0
# data
# the tum dataset directory, change it to yours! 
dataset_dir: /home/jinyao/SLAM_Datasets/rgbd_dataset_freiburg1_desk

#/home/jinyao/SLAM_Datasets/rgbd_dataset_freiburg1_360
#/home/jinyao/SLAM_Datasets/rgbd_dataset_freiburg1_desk
#/home/jinyao/SLAM_Datasets/rgbd_dataset_freiburg1_xyz
#/home/jinyao/SLAM_Datasets/rgbd_dataset_freiburg2_360_hemisphere
#/home/jinyao/SLAM_Datasets/rgbd_dataset_freiburg2_desk
#/home/jinyao/SLAM_Datasets/rgbd_dataset_freiburg2_desk_with_person
#/home/jinyao/SLAM_Datasets/rgbd_dataset_freiburg3_long_office_household

# camera intrinsics
# fr1
camera.fx: 517.3
camera.fy: 516.5
camera.cx: 325.1
camera.cy: 249.7

# distortion coefficients
camera.k1: 2.6409664444764552e-01
camera.k2: -8.1089926788322986e-01
camera.p1: -1.2332180561355017e-03
camera.p2: 1.1770923311935535e-03
camera.k3: 5.7508917737950627e-01 

camera.depth_scale: 5000

# VO paras
num_of_features: 400
orb_sacle_factor: 1.2
orb_level_pyramid: 8
min_match_ratio: 0.5
max_num_lost: 5
min_inliers_rate: 0.5
max_map_points: 10000
keyframe_rotation: 0.1
keyframe_translation: 0.1
frame_max_rot:1
frame_max_trans:1
