%YAML:1.0
# data
# the tum dataset directory, change it to yours! 
dataset_dir: /home/jinyao/SLAM_Datasets/rgbd_dataset_freiburg2_desk

# camera intrinsics
# fr1
camera.fx: 517.3
camera.fy: 516.5
camera.cx: 325.1
camera.cy: 249.7

# distortion coefficients
camera.k1: 2.6409664444764552e-01
camera.k2: -8.1089926788322986e-01
camera.p1: -1.2332180561355017e-03
camera.p2: 1.1770923311935535e-03
camera.k3: 5.7508917737950627e-01 

camera.depth_scale: 5000

# VO paras
number_of_features: 500
scale_factor: 1.2
level_pyramid: 8
match_ratio: 2.0
max_num_lost: 10
min_inliers: 10
keyframe_rotation: 0.1
keyframe_translation: 0.1
